globalReplacements:
  - key: CustomerName
    type: String
    value: ${customer.slug}
  - key: AcceleratorPrefix
    type: String
    value: ${lza.accelerator_prefix}
  - key: HomeRegion
    type: String
    value: ${aws.region}
